services:
  # PHP Application Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: campus-job-portal-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    environment:
      - APP_NAME="Campus Job Portal"
      - APP_ENV=production
      - APP_KEY=base64:Yf0v/wZpur05I3Q1I/j9GXFrlDHwBbcZOShwKrhQaNs=
      - APP_DEBUG=false
      - APP_TIMEZONE=Asia/Jakarta
      - APP_URL=http://128.199.31.100
      - LOG_CHANNEL=stack
      - LOG_DEPRECATIONS_CHANNEL=null
      - LOG_LEVEL=error
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=campus_job_portal
      - DB_USERNAME=laravel_user
      - DB_PASSWORD=laravel_password
      - BROADCAST_DRIVER=log
      - CACHE_DRIVER=file
      - FILESYSTEM_DISK=local
      - QUEUE_CONNECTION=database
      - SESSION_DRIVER=file
      - SESSION_LIFETIME=120
      - MEMCACHED_HOST=127.0.0.1
      - REDIS_HOST=127.0.0.1
      - REDIS_PASSWORD=null
      - REDIS_PORT=6379
      - MAIL_MAILER=smtp
      - MAIL_HOST=mailpit
      - MAIL_PORT=1025
      - MAIL_USERNAME=null
      - MAIL_PASSWORD=null
      - MAIL_ENCRYPTION=null
      - MAIL_FROM_ADDRESS="hello@example.com"
      - MAIL_FROM_NAME="Campus Job Portal"
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_BUCKET=
      - AWS_USE_PATH_STYLE_ENDPOINT=false
      - PUSHER_APP_ID=
      - PUSHER_APP_KEY=
      - PUSHER_APP_SECRET=
      - PUSHER_HOST=
      - PUSHER_PORT=443
      - PUSHER_SCHEME=https
      - PUSHER_APP_CLUSTER=mt1
      - VITE_APP_NAME="Campus Job Portal"
      - VITE_PUSHER_APP_KEY=""
      - VITE_PUSHER_HOST=""
      - VITE_PUSHER_PORT=443
      - VITE_PUSHER_SCHEME=https
      - VITE_PUSHER_APP_CLUSTER=mt1
    networks:
      - campus-job-portal
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "php", "-v"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    entrypoint: [
      "/bin/sh", "-c",
      "./wait-for-db.sh db 3306 laravel_user laravel_password &&
       chown -R www-data:www-data /var/www/storage /var/www/bootstrap/cache &&
       chmod -R 775 /var/www/storage /var/www/bootstrap/cache &&
       php artisan cache:clear &&
       php artisan route:clear &&
       php artisan view:clear &&
       php artisan storage:link --force &&
       php artisan config:cache &&
       php artisan route:cache &&
       php artisan view:cache &&
       php-fpm"
    ]

  # Nginx Web Server Service
  webserver:
    image: nginx:alpine
    container_name: campus-job-portal-webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/logs:/var/log/nginx
    networks:
      - campus-job-portal
    depends_on:
      app:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # MySQL Database Service
  db:
    image: mysql:8.0
    container_name: job_portal_db_prod
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secure_root_password_2024
      MYSQL_DATABASE: campus_job_portal
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
      MYSQL_ROOT_HOST: '%'
    volumes:
      - dbdata_prod:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d
    networks:
      - campus-job-portal
    ports:
      - "3306:3306"
    command: >
      --default-authentication-plugin=mysql_native_password
      --bind-address=0.0.0.0
      --innodb-buffer-pool-size=256M
      --max-connections=200
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-ularavel_user", "-plaravel_password"]
      interval: 20s
      timeout: 15s
      retries: 10
      start_period: 60s

  # Queue Worker Service
  queue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: job_portal_queue_prod
    restart: unless-stopped
    volumes:
      - ./storage:/var/www/storage
      - ./wait-for-db.sh:/wait-for-db.sh
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=campus_job_portal
      - DB_USERNAME=laravel_user
      - DB_PASSWORD=laravel_password
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_KEY=base64:Yf0v/wZpur05I3Q1I/j9GXFrlDHwBbcZOShwKrhQaNs=
      - QUEUE_CONNECTION=database
    networks:
      - campus-job-portal
    depends_on:
      db:
        condition: service_healthy
      app:
        condition: service_started
    entrypoint: ["/bin/bash", "-c"]
    command:
      - |
        chmod +x /wait-for-db.sh
        /wait-for-db.sh db
        sleep 15
        php artisan queue:work --sleep=3 --tries=3 --max-time=3600 --timeout=300

volumes:
  dbdata_prod:
    driver: local

networks:
  campus-job-portal:
    driver: bridge