name: CI/CD Pipeline

on:
  push:
    branches: [ main, master, develop ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/berkatps/campus-job-portal
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,format=long
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Setup test environment
        if: github.event_name == 'pull_request'
        run: |
          docker-compose up -d
          docker-compose exec -T app composer install
          docker-compose exec -T app php artisan key:generate
          docker-compose exec -T app php artisan migrate:fresh --seed
      - name: Run tests
        if: github.event_name == 'pull_request'
        run: |
          docker-compose exec -T app php artisan test
      - name: Deploy to production
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        run: |
          # Add deployment steps here - for example:
          # - SSH into server and pull latest image
          # - Run docker-compose up -d
          #
          # Example:
          # uses: appleboy/ssh-action@master
          # with:
          #   host: ${{ secrets.HOST }}
          #   username: ${{ secrets.USERNAME }}
          #   key: ${{ secrets.SSH_KEY }}
          #   script: |
          #     cd /path/to/project
          #     docker pull ghcr.io/berkatps/campus-job-portal:latest
          #     docker-compose up -d
          #     docker-compose exec -T app php artisan migrate --force
          #     docker-compose exec -T app php artisan optimize:clear
          echo "Deployment script would run here"
